### ISSUE TITLE
Create image directory and move image files

### ISSUE THREAD

**Issue by naokidney** [kristinejosami/first-git-project#4]
In `html` directory, html files and image files are mixed.
Would you create `image` directory in `html` directory, and put image files into the `image` directory?

**Comment by kristinejosami** [comment]
Should I create another branch for this or just use the fix_file_name branch?

**Comment by kristinejosami** [comment]
@naokitcut I'm done moving it

**Comment by kristinejosami** [comment]
@naokitcut is this one done already?
